intro-to-web-development/activity-layers.md, intro-to-web-development/intro-to-clients-servers-http.md, intro-to-web-development/intro-to-web-development.instructor.md, intro-to-web-development/sequence-diagrams.md, intro-to-web-development/web-applications-and-layers.md
At the top: Instructor file for the topic
1. Web Applications and Layers
2. Intro to Clients Servers
3. Sequence Diagrams
4. Activity
=> intro-to-web-development: content without diagrams

intro-to-sql/problem-set-intro-to-sql.md
I think it's important to make it very clear to students that for most of these questions the Learn checkmark doesn't mean they've written the commands correctly and its important for them to check
=> intro-to-sql: Add notes to problem set explanations

building-an-api/create-and-read.md
Some of the lesson text was changed from predict to plan. This updates the question checkboxes to match the verbiage.
=> aligns question text to lesson changes

more-selecting-in-sql/ordering.md
order by price should be ascending by default
=> change order to ascending

testing-our-apis/using-tests.md
Small changes to conform with our new best practices:
- prefer `make_response` over `Response`
- includes importing the `Book` model
Adding Claire so she has visibility on this in case she's starting the video
=> updating test lesson with minor details

deployment/deploying-to-heroku.md
Until Learn can support main for projects, the lesson should probably match our project branch name to reduce student headache/confusion
=> Update git push command to work with local master branch

intro-to-sql/sql-fixtures/intro-to-sql-problemset.sql
The product table had a duplicate product id and no primary key constraint.
=> fixes constraints on table and removes duplicate data

requests-and-responses/problem-set-requests-with-python.md
A PR to switch the problem set questions to regex, as long as they enter a number with a decimal it'll accept it.  I also added an explanation section with the answer from the previous cohort.  This way they'll know if they're in the ballpark.
=> change questions to use regex

relationships-in-sqlalchemy/one-to-many.md
Bailey found a typo in the lesson, good to merge?
=> Missing parent class for Author model - Bailey suggested

api-1-setup-read/flask-setup.md, api-1-setup-read/hello-world-routes.md, api-1-setup-read/intro-to-hello-books.md, api-1-setup-read/read-all-books.md, api-2-read-404s/read-one-book.md
- Updated Intro to Hello Books doc
- Made formatting/heading changes for consistency
- Added starting and ending branches to each lesson
=> Updates to the 1) Building an API - Setup and Read Topic

api-2-read-404s/400-and-404s.md
Do you think we need a PR for inserting videos?
=> Add error handling playlist

api-1-setup-read/activity-solar-system-api.instructor.md, api-1-setup-read/intro-to-hello-books.md, api-8-deployment/deploying-to-heroku.md, config.yaml
- Updated Deploying to Heroku format
- Added to the callout in Intro to Hello Books
- Changes Solar System Activities to type: Lesson so instructors can decide whether to make it visible or not
=> Deployment and Solar System update

api-3-database-models-read/resolving-schema-conflicts.md, config.yaml
- This is taken from Miguel Grinberg's blog
- The solutions still need to be tested and the code adapted to the Book model
- I marked it as an instructor doc for the time being
=> Format resolving schema conflicts lesson

api-2-read-404s/400-and-404s.md, api-3-database-models-read/models-setup.md, api-5-more-queries/query-params.md, api-6-testing/dot-env-and-the-test-db.md
just noticed that prettier reformatted tables!
=> change exiting to existing and add return to code table

api-6-testing/read-one-book-test.md
Change starting branch name from `06c-using-setup` to `06c-using-tests` and update the ending branch name from `06d-read-one-book-test` to `06d-read-one-books-test` to match the branch names in GitHub.
=> D17 branch: Update Building an API Part 6 starting & ending branch names

api-6-testing/read-one-book-test.md
Change starting branch name from `06c-using-setup` to `06c-using-tests` and update the ending branch name from `06d-read-one-book-test` to `06d-read-one-books-test` to match the branch names in GitHub.
=> main branch: Update Building an API Part 6 starting & ending branch names

api-10-many-to-many/join-table-many-to-many.md, api-10-many-to-many/routes-many-to-many.md, api-8-relationships-in-sqlalchemy/nested-routes-in-flask.md, api-8-relationships-in-sqlalchemy/one-to-many.md
Changes:
- Incorporate refactoring changes from pt. 7 of Building an API series into the code examples in parts 8-10. 
- In pt. 10 routes-many-to-many.md, updates language around the `to_dict` function to reflect that we want to update the existing function from pt. 7
- Also fixes a couple issues with angle brackets inside `<code>` tags causing the text to disappear
=> Update code examples in Building an API pts. 8-10

api-6-testing/using-tests.md
[asana ticket](https://app.asana.com/0/1201700438643002/1202228058753083/f)
A stab at where I imagined this sentence would go, based on the rest of this lesson.
=> Finish sentence in Lesson 06/testing Goals

intro-to-sql/problem-set-intro-to-sql.md
Update intro to sql problem set instructions to be more explicit that the sql dump needs to be in the directory where the commands using it will be executed.
=> Update Intro To SQL Problem Set instructions

api-1-setup-read/intro-to-flask.md
Changes for Unit 2 to update Flask
Asana task: https://app.asana.com/0/1205655776549324/1207004723163587/f
=> Update documentation links for Flask 3.0.x

api-3-database-models-read/models-migrations.md
[Asana ticket](https://app.asana.com/0/1205655776549324/1207004723163599/f)
Changes:
- Comment out videos & add marker to find the commented out section in the future. 
- Update the project structure diagram to reflect new folders. 
- Update SQLAlchemy docs link
=> Building an API Pt. 3 - Lesson 1 Updates

api-3-database-models-read/problem-set-create-read.md, api-3-database-models-read/resolving-schema-conflicts.md
[Pt. 3 Asana ticket](https://app.asana.com/0/0/1206697443678568/f)
[Pt. 3 Resolving Schema Conflicts Ticket](https://app.asana.com/0/1201700438643002/1207004723163603/f)
Resolving Schema Conflicts
- Update code snippets to use newer model syntax 
- Update Terminal instructions for recreating a database (I could not use the `dropdb`/`createdb` commands listed, so I gave the full psql commands)
Problem Set
- Update Problem Set file to include that create should send back a record not just a success message
=> Building an API Pt. 3 - "Resolving Schema Conflicts" & "Problem Set" Flask updates 

api-6-testing/problem-set-testing.md
[Pt. 6 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678572/f)
[Pt. 6 Problem Set ticket](https://app.asana.com/0/1205655776549324/1207017851991906/f)
=> Building an API pt. 6 - Problem Set Updates

api-1-setup-read/intro-to-hello-books.md
[Asana Ticket](https://app.asana.com/0/1205655776549324/1207668515823781/f)
Changes:
- Adds git commands for creating & pushing the new branch `main`, then links to GitHub docs for how to change the default branch.
- Also makes some small phrasing changes to a couple bullet points in the same lesson page for clarity.
=> Add instruction to set the default branch of hello-books-api to main

api-8-relationships-in-sqlalchemy/nested-routes-in-flask.md
[Pt. 8 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678574/f)
[Pt. 8 Lesson 2 ticket](https://app.asana.com/0/1205655776549324/1207017851991912/f)
=> Building an API pt. 8 - lesson 2: 'One-to-Many: Nested Routes'

api-8-relationships-in-sqlalchemy/nested-routes-in-flask.md, api-8-relationships-in-sqlalchemy/problem-set-one-to-many.md, config.yaml
[Pt. 8 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678574/f)
[Pt. 8 Problem Set ticket](https://app.asana.com/0/1205655776549324/1207017852288091/f)
Also includes a fix for Pt. 8 lesson 2 where I forgot to update one of the code examples.
=> Building an API pt. 8 - Add Problem Set page

api-9-deployment/deploying-to-render.md
[Pt. 9 Asana ticket](https://app.asana.com/0/1205655776549324/1206934546187432/f)
[Pt. 9 Lesson 2 ticket](https://app.asana.com/0/1205655776549324/1207017851991917/f)
There is no lesson 1 ticket since that only covers general information about what deployment is; the video there looks at the lesson, but does not show outdated code.
=> Flask Updates: Building an API pt. 9, lesson 2: Deploying to Render

api-10-many-to-many/genre-many-to-many.md
[Pt. 10 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678575/f)
[Pt. 10 Lesson 1 ticket](https://app.asana.com/0/1205655776549324/1207017851991918/f)
=> Flask Updates: BaA pt. 10 lesson 1 - Many-to-Many: Genres

api-10-many-to-many/routes-many-to-many.md
[Pt. 10 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678575/f)
[Pt. 10 Lesson 3 ticket](https://app.asana.com/0/1205655776549324/1207017851991920/f)
=> Flask Updates: BaA pt. 10 lesson 3 - Many-to-Many: Nested Routes

api-10-many-to-many/problem-set-many-to-many.md, config.yaml
[Pt. 10 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678575/f)
[Pt. 10 Problem Set ticket](https://app.asana.com/0/1205655776549324/1207017852288093/f)
=> Add Building an API pt. 10 Problem Set page

api-7-refactoring/refactor-validate-book.md
[Building an API Part 7 has 200 plus string message regression
](https://app.asana.com/0/1205655776549324/1208673704309219)
=> Update tests shown for update_book and delete_book to remove 200 status code.

intro-to-api-design/designing-responses.md, intro-to-api-design/intro-to-api-design.instructor.md
[Include 204 No Content as possible (preferred?) response codes for PUT/DELETE](https://app.asana.com/0/1205655776549324/1208546343899252)
=> Update Designing Responses to show returning 204 for successful PUT and DELETE requests

requests-and-responses/sending-requests-with-python.md
[Task](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1210193230464615?focus=true): Refresh instructions for installing requests
=> Update instructions for installing the requests package

api-7-refactoring/refactor-validate-book.md
Asana Task
Changes
- Update the tests for update and delete routes in "BaA Pt. 7" > "Refactoring for Future Features" lesson to use current api pattern where update and delete do not return a response body.
=> Building an API pt. 7 - Replace tests for update & delete refactors
